### ISSUE TITLE
Fatal error: Call to private Transliterator::__construct() 

### ISSUE THREAD

**Issue by ttasovac** [umpirsky/Transliterator#4]
how should one instantiate the Transliterator? the readme says this:
 
    $transliterator = new Transliterator(Settings::LANG_SR);

but the above gives me:

    Fatal error: Call to private Transliterator::__construct() from invalid context in /var/www/abc.dev/html/methods/forms.php on line 43

any hints would be greatly appreciated.

**Comment by umpirsky** [comment]
Looks fine @ttasovac.

That is how I instantiate it in [tests](https://github.com/umpirsky/Transliterator/blob/master/tests%2FTransliterator%2FTransliteratorTest.php#L77). It should work.

Can you create a test script or provide full example php file?

**Comment by ttasovac** [comment]
Хвала, Саша! :) The problem may be that I am not using Composer and autoloading etc. So I did this:

    require_once('vendor/umpirsky/src/Transliterator/Transliterator.php');
    $transliterator = new Transliterator(Settings::LANG_SR);

and I ended up with the above error. 

Sorry to be a pain —  I'm sure this is just me not understanding something totally basic.

**Comment by umpirsky** [comment]
@ttasovac Why not using compser? :)

May it be you have old or changed version of Transliterator. Is constructor private in your local copy?

**Comment by ttasovac** [comment]
no, i have the latest version —  i really couldn't make any sense of this error. but i did manage to get the transliterator to work with this:

    require_once('vendor/umpirsky/src/autoload.php');
		$transliterator = new \Transliterator\Transliterator("sr");

so no more drama from me, ok? :)

**Comment by umpirsky** [comment]
Oh, ok, that is the recommanded way. :)
